### ISSUE TITLE
Chapter 5, page 162 - console error due to 'same origin' policy

### ISSUE THREAD

**Issue by abahler** [semmypurewal/LearningWebAppDev#20]
In trying to obtain the JSON from the Flickr URL provided, the Chrome console shows this error:

```
XMLHttpRequest cannot load http://api.flickr.com/services/feeds/photos_public.gne?tags=dogs&format=json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access.
```

The Chrome fix detailed on page 156 ("Overcoming Browser Security Restrictions") only applies to JSON files on the same server. I'm using Mac OS X 10.9 (Mavericks), running the page through MAMP.

Apologies if this is my error and doesn't belong on the Issues tracker.

**Comment by samirgandhi19** [comment]
This conversation helped a lot, thank you.
