### ISSUE TITLE
Questions about install nTwitter

### ISSUE THREAD

**Issue by edgenard** [semmypurewal/LearningWebAppDev#57]
On the Errata for [page] (http://learningwebappdev.com/errata/chapter6/2014/06/07/chapter-6-incorrect-ls-command.html) 197 you mention the `ls node_modules` is wrong. However, `node_modules` was installed in the `Twitter` directory when I ran `npm install ntwitter` from it but I don't see `express`. 

Is this discrepancy important? Should I make sure that `node_modules` is in the the `app` directory? What about `express`?  Do I need to make sure it is in the `Twitter` directory?

Thanks

**Comment by semmypurewal** [comment]
@samseen and I have worked through his issue over e-mail, and I haven't heard from @edgenard again about this.

@edgenard, please feel free to reopen this issue or open a new one if you're still hitting these problems!
