### ISSUE TITLE
Double quotes

### ISSUE THREAD

**Issue by alsfurlan** [semmypurewal/LearningWebAppDev#75]
Hi!
First of all, congradulations! Your book is very educacional. I am using to teatching at my class of web technologies. It is the best I found.

I noticed you wrote double quotes in JavaScript, but the convention is the single quotes.

**Comment by samseen** [comment]
Yeah @alsfurlan he made a comment about it in the book. At the Preface, page xv. 

> For the most part, I’ve followed idiomatic JavaScript, but there are a few places I’ve
> strayed. For example, I preferred double quotes instead of single quotes for strings,
> primarily because I’ve been working under the assumption that students may be coming
> from a Java/C++ background. I choose to use quotes around property names in object
> literals so that JSON doesn’t look too different from JavaScript objects. I also use $ as
> the first character in variables that are pointing to jQuery objects. I find that it maintains
> clarity and makes the code a little more readable for novices.

Good luck with the book, I've also found it to be very interesting and educational.

**Comment by alsfurlan** [comment]
Yeah @samseen! I read this, but have forget. Thanks!

**Comment by semmypurewal** [comment]
Thanks for answering this one, @samseen!

@alsfurlan, thank you very much for the feedback, and thanks for using my book in your class. Feel free to ping me here or via e-mail if you have any other questions!

**Comment by alsfurlan** [comment]
@semmypurewal  Your book already have translation for portuguese?
