### ISSUE TITLE
Vagrant: Error installing cf

### ISSUE THREAD

**Issue by samirgandhi19** [semmypurewal/LearningWebAppDev#82]
I am getting a CloudFoundry error when creating the guest machine (vagrant up). Have not touched vagrant file. running Vbox:5.0.2 vagrant:1.8.4

bottom portion of error: 
`=> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   ruby1.9.1
==> default: Suggested packages:
==> default:   ruby1.9.1-examples ri1.9.1 graphviz
==> default: Recommended packages:
==> default:   ruby1.9.1-full
==> default: The following NEW packages will be installed:
==> default:   ruby1.9.1 ruby1.9.3
==> default: 0 upgraded, 2 newly installed, 0 to remove and 189 not upgraded.
==> default: Need to get 50.1 kB of archives.
==> default: After this operation, 431 kB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main ruby1.9.1 i386 1.9.3.0-1ubuntu2.10 [36.9 kB]
==> default: Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/universe ruby1.9.3 all 1.9.3.0-1ubuntu2.10 [13.2 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 50.1 kB in 0s (193 kB/s)
==> default: Selecting previously unselected package ruby1.9.1.
==> default: (Reading database ... 
==> default: 46107 files and directories currently installed.)
==> default: Unpacking ruby1.9.1 (from .../ruby1.9.1_1.9.3.0-1ubuntu2.10_i386.deb) ...
==> default: Selecting previously unselected package ruby1.9.3.
==> default: Unpacking ruby1.9.3 (from .../ruby1.9.3_1.9.3.0-1ubuntu2.10_all.deb) ...
==> default: Processing triggers for man-db ...
==> default: Setting up ruby1.9.1 (1.9.3.0-1ubuntu2.10) ...
==> default: update-alternatives: 
==> default: using /usr/bin/gem1.9.1 to provide /usr/bin/gem (gem) in auto mode.
==> default: update-alternatives: 
==> default: using /usr/bin/ruby1.9.1 to provide /usr/bin/ruby (ruby) in auto mode.
==> default: Setting up ruby1.9.3 (1.9.3.0-1ubuntu2.10) ...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Building native extensions.  This could take a while...
==> default: ERROR:  Error installing cf:
==> default: 	json_pure requires Ruby version ~> 2.0.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

any thoughts?

**Comment by semmypurewal** [comment]
Yes, we've seen this issue. There's a problem with the CloudFoundry client dependencies that causes this. The VM should still work, but the cf client will probably give you trouble. Some folks have managed to work around this, but I haven't gotten clarity into how.

The right thing to do is to install Ruby 2.0 on the VM, but I haven't figured out a simple way to do that through the VagrantFile yet.

**Comment by samirgandhi19** [comment]
cool, so i did
```terminal 
sudo apt-get install ruby 2.0.0
ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
sudo gem install cf
```
then a cf, which shows 
```terminal
/home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/i686-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Cloud Foundry Command Line Interface, version [5.4.7]
  Use 'cf help [command]' for command details.
  For docs and support visit http://support.cloudfoundry.com
```

but I keep getting a crash when I try logging into cf. 

```terminal 
vagrant@precise32:~$ cf target api.run.pivotal.io
/home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/i686-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Setting target to https://api.run.pivotal.io... OK
vagrant@precise32:~$ cf login
/home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/i686-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
target: https://api.run.pivotal.io

Email> ****

Password> ********

Authenticating... OK
Time of crash:
  2016-10-19 16:29:49 +0000

TypeError: can't convert nil into an exact number

cfoundry-4.7.2.rc1/lib/cfoundry/auth_token.rb:56:in `at'
cfoundry-4.7.2.rc1/lib/cfoundry/auth_token.rb:56:in `expiration'
cfoundry-4.7.2.rc1/lib/cfoundry/auth_token.rb:60:in `expires_soon?'
cfoundry-4.7.2.rc1/lib/cfoundry/baseclient.rb:137:in `needs_token_refresh?'
cfoundry-4.7.2.rc1/lib/cfoundry/baseclient.rb:82:in `request'
cfoundry-4.7.2.rc1/lib/cfoundry/baseclient.rb:66:in `get'
cfoundry-4.7.2.rc1/lib/cfoundry/v2/model_magic/client_extensions.rb:36:in `block (2 levels) in add_client_methods'
cfoundry-4.7.2.rc1/lib/cfoundry/v2/model_magic/client_extensions.rb:99:in `block (2 levels) in add_client_methods'
cf-5.4.7/lib/cf/cli/populators/organization.rb:16:in `choices'
cf-5.4.7/lib/cf/cli/populators/populator_methods.rb:48:in `prompt_user'
cf-5.4.7/lib/cf/cli/populators/populator_methods.rb:38:in `get_object'
cf-5.4.7/lib/cf/cli/populators/populator_methods.rb:13:in `populate_and_save!'
cf-5.4.7/lib/cf/cli/populators/target.rb:8:in `populate_and_save!'
cf-5.4.7/lib/cf/cli/start/login.rb:80:in `login'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-5.4.7/lib/cf/cli.rb:195:in `block (2 levels) in execute'
cf-5.4.7/lib/cf/cli.rb:202:in `save_token_if_it_changes'
cf-5.4.7/lib/cf/cli.rb:194:in `block in execute'
cf-5.4.7/lib/cf/cli.rb:123:in `wrap_errors'
cf-5.4.7/lib/cf/cli.rb:190:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-5.4.7/bin/cf:18:in `<top (required)>'
/home/vagrant/.rvm/rubies/ruby-2.3.0/bin/cf:23:in `load'
/home/vagrant/.rvm/rubies/ruby-2.3.0/bin/cf:23:in `<main>'
ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

any thoughts here?

**Comment by samirgandhi19** [comment]
okay, I think my problem is that it was not the latest version of cloud foundry. 

I cannot figure out how to install the latest cf/cf cli on the guest machine. please help. cd

**Comment by samirgandhi19** [comment]
The instructions for linux at https://docs.cloudfoundry.org/cf-cli/install-go-cli.html worked. but I just needed to use sudo su, not just sudo.
